name: push image on registry
on:
  # pull_request:
  #   types: [closed]
  push:
    branches:
    - feature/img_index
jobs:
  image_and_index:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to this repo
        uses: actions/checkout@v4
      - name: Login to AWS 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1
      # - name: Deploy on ECS
      #   run: |
      #     aws ecs update-service --cluster Cluster-Proyecto --service My-ecs-service --force-new-deployment
      - name: Deploy on S3
        run: |
          aws s3 cp ./index.html s3://newyork-bucket2 --recursive 